### ISSUE TITLE
Can I insert the name from an existing input field value?

### ISSUE THREAD

**Issue by zizzzl** [jessepollak/card#251] opened 2016-05-26 22:23 UTC
The customer has already entered his or her name before reaching the credit card form.  I can insert this value into the name input box, but it doesn't show up on the card image.  How can the name be inserted in a way that it shows up in the card image?  Thank you.

**Comment by johnbacon** [comment] 2016-06-22 19:01
+1 to this issue. We can likely hack it by simulating a keyup or change event, but it'd be great to be in the plugin itself.

**Comment by jonathanazulay** [comment] 2016-07-15 20:26
+1

In my application, the name to use for the card must match the currently logged in user. So I created an input hidden field with the name as value and then created the card but only the placeholder name gets rendered.

Tried all workarounds I could think of (dispatchEvent #170, calling card.render()) but nothing works.

**Comment by lazharichir** [comment] 2016-08-18 20:24
I have the customer also entering his name before so would be great if we could programmatically change the name's value.

**Comment by jessepollak** [comment] 2016-09-19 00:11
Closing as a duplicate of #184. Would love to accept a PR for this functionality!

**Closed by jessepollak** 2016-09-19 00:11 UTC
