### ISSUE TITLE
Not working properly at android mobile chrome

### ISSUE THREAD

**Issue by devqualwebs** [jessepollak/card#317] opened 2017-01-18 06:54 UTC
I am facing an issue when I am using the website on mobile device android google chrome. The card number input, expiry date, CVV all input fields neither formatting the inputs not validating them allow to the user to input string also at the place of digits.

**Comment by BallisticPain** [comment] 2017-02-08 15:27
@devqualwebs 
Care to share some code of how you have this setup so we could offer some assistance in getting it to work for you?

**Comment by h3kno** [comment] 2017-03-07 01:06
Just ran into this bug @devqualwebs. 

I believe the problem lies in QJ. It is not properly binding the key events in android chrome. Any ideas on why that is @BallisticPain @jessepollak ?

**Comment by nickooolas** [comment] 2017-04-24 21:52
Getting quite a few failed payments because of this intermittent error with Android devices 😢  @jessepollak 

Here's the user agents that are getting it - essentially, they can't enter the slash "/", and then our payment fails from Expiry Validation error:

**ANDROID USER AGENTS NOT WORKING**
Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-G930F Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile Safari/537.36

Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-T355Y Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Safari/537.36

Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-N920I Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile Safari/537.36

Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-G900I Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile Safari/537.36

**CONFIRMED ANDROID AGENTS WORKING OK**
Mozilla/5.0 (Linux; Android 4.4.2; Tab2A7-10F Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.132 Safari/537.36

Mozilla/5.0 (Linux; Android 6.0.1; SM-G900I Build/MMB29M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.132 Mobile Safari/537.36

Also, I can confirm, when this occurs, there are **no console errors occurring** (can confirm that from client-side error reporting script), they are just unable to type in the expiry date fully on these devices.

Looks like this might be something to do with either the Chrome Version?

![slash](https://cloud.githubusercontent.com/assets/12520584/25360331/ff730c2e-298b-11e7-86db-1bb1febd48be.jpg)

**Comment by nickooolas** [comment] 2017-04-24 22:28
Related? 

https://github.com/braintree/braintree-web/issues/245

Seems like it might be something to with the `SamsungBrowser/4.0`

**Comment by luishmcmoreno** [comment] 2017-05-09 18:45
The problem is keypress event is not fired on most of chrome android devices. Changing this to keydown doesn't work because these browsers send event.which = 229 (combined characters). 

Changing this to keyup doesn't work too, because in this moment, the input already have the value and event.preventDefault() doesn't matter.

To change to keyup requires change all the lib's logic.

**Comment by nickooolas** [comment] 2017-09-22 02:47
Any insights on this one @luishmcmoreno as to how it could be monkey patched or fixed otherwise? It's costing a lot of conversions for us with Android phones just because a simple "/" isn't being entered like it does normally.

**Comment by luishmcmoreno** [comment] 2017-09-22 19:27
Hey @nickooolas ... Try this https://gist.github.com/luishmcmoreno/45839565828ae3597816b98fa83bf754 . I've made some changes on the lib and it worked for me. I didn't all the necessary tests to create a pull request but to my needs, it worked.

**Comment by nickooolas** [comment] 2017-09-23 01:22
@luishmcmoreno awesome work, thanks for the quick reply and patch on this one! :)

**Comment by luishmcmoreno** [comment] 2017-09-26 05:20
it worked to you @nickooolas ? The problem seems to be in the payments lib, not here.

**Comment by mostafa-saqr** [comment] 2017-11-21 17:46
it worked for me but expiry date input (length) not work so it able to take 1000 digit :)

**Comment by stefmabo** [comment] 2017-11-23 21:39
@mostafa-saqr , you are right!

Any solution?

**Comment by chayglass** [comment] 2018-02-23 21:01
I think this is the same issue - when I type in a credit card number on my S7 Edge - Chrome 64 - after about the 5th digit, it repeats all 5 digits (so "45140" turns into "4514045140"). I can paste okay, just not type.

**Comment by melloware** [comment] 2020-12-03 13:06
duplicate of #199 you can..

> working on android devices with input type="tel" instead of input type="text"

**Closed by melloware** 2020-12-03 13:06 UTC
