### ISSUE TITLE
Roadmap for eCheck

### ISSUE THREAD

**Issue by MonteShaffer** [jessepollak/card#300] opened 2016-12-04 15:43 UTC
Is there a roadmap to implement this same methodology for eChecks.

Bank Name
Routing Number
Account Number
Account Type

**Comment by MonteShaffer** [comment] 2016-12-07 15:37
Some code for a valid routing number ...

```

// https://en.wikipedia.org/wiki/Routing_transit_number#MICR_Routing_number_format
function validRoutingNumber(str)
	{
	str = trim(str);
	console.log("validRoutingNumber: "+str);
	if(!validNumber(str)) { return false; }
	var len = str.length;
		console.log(len);
	if(len != 9) { return false; }
	var sum = 0;
		var multiply = [3,7,1,3,7,1,3,7,1];
	for(var i=0;i<len;i++)
		{
		sum += multiply[i]*parseInt(str.charAt(i));
		}
		console.log(sum);
	if(sum % 10 != 0) { return false; }
	
	return true;
	}

```

**Comment by BallisticPain** [comment] 2016-12-07 15:45
@MonteShaffer 
I'm happy to see you excited about this project. Please keep the requests coming, and as with all of them you're welcome to submit a PR, or someone will pickup the request when they have time. :)

Thanks!

**Comment by melloware** [comment] 2020-12-03 18:06
Duplicate of https://github.com/jessepollak/card/issues/410

**Closed by melloware** 2020-12-03 18:06 UTC
