### ISSUE TITLE
Card resets to default image when form validation fails.

### ISSUE THREAD

**Issue by 3CWebDev** [jessepollak/card#245] opened 2016-05-05 19:16 UTC
Currently, if the user types in the CC info and submits the form but the validation fails (if the CVV is not valid for example) then the form reloads via ajax and the info is still in the form (CC number for example) the card image no longer shows the input values or the visa/MC/etc image (it has reset back to the default).

Is this a bug or is there something I could be doing in the processing to for card to retain its values after a failed form submit?

**Comment by dep** [comment] 2016-05-24 12:02
I also wonder if there's a way to 'trigger' the card event when the form comes back with an error.  Currently the input gets re-populated as expected, but trying to trigger keyup, keydown, blur, etc on the input, doesn't cause the card image to trigger.

**Comment by dep** [comment] 2016-05-24 12:12
Just wanted to follow-up that this actually works.  I just ran this on pageload if an error existed (the jQuery triggers don't appear to work but native JS methods do:

var evt = document.createEvent('HTMLEvents');
evt.initEvent('keyup', false, true);
document.getElementById('field_that_failed').dispatchEvent(evt);

**Comment by 3CWebDev** [comment] 2016-05-24 14:59
Thanks dep, this worked for me. A quick implementation I put together and is working: 
```javascript
jQuery(document).ready(function(){ 
  var evt = document.createEvent('HTMLEvents');
  evt.initEvent('keyup', false, true);
  if (jQuery("#edit-commerce-payment-payment-details-credit-card-owner").length ) {
    document.getElementById('edit-commerce-payment-payment-details-credit-card-owner').dispatchEvent(evt);
  }
  
  if (jQuery("#edit-commerce-payment-payment-details-credit-card-number").length ) {
    document.getElementById('edit-commerce-payment-payment-details-credit-card-number').dispatchEvent(evt);
  }
  
  if (jQuery("#edit-commerce-payment-payment-details-credit-card-expiry").length ) {
    document.getElementById('edit-commerce-payment-payment-details-credit-card-expiry').dispatchEvent(evt);
  }
  
  if (jQuery("#edit-commerce-payment-payment-details-credit-card-code").length ) {
    document.getElementById('edit-commerce-payment-payment-details-credit-card-code').dispatchEvent(evt);
  } 
}) 
```

**Comment by jessepollak** [comment] 2016-09-19 00:17
Closing this as a duplicate of #166.

**Comment by jessepollak** [comment] 2016-09-19 00:18
And by #166 I actually mean #184. Thanks for reporting!

**Closed by jessepollak** 2016-09-19 00:17 UTC
