### ISSUE TITLE
Does not work with iOS4 and Android4

### ISSUE THREAD

**Issue by MimRaCreative** [jessepollak/card#269] opened 2016-08-08 23:48 UTC
Does not leave space when writing the card number and the card size is not changed. See pls for example https://www.camasirpijama.com/ 
Could you pls help me...

**Comment by Iftahh** [comment] 2016-09-18 14:23
For me (testing in Android Chrome) - I found everything works **if** I change the input type of number/expiry/cvc  to "tel" -

this also sets a proper digits keyboard and has the neat side affect of fixing the `keypress` and `e.which` events.

Would love to hear if it fixes on other devices/browsers as well.

**Comment by jessepollak** [comment] 2016-09-18 23:57
@jacobcarrington from your digging, do you think there is a chance we should make in the library to help resolve this? Thanks!

**Comment by jessepollak** [comment] 2016-09-19 00:13
I believe this is also a duplicate of #199. Closing in favor of that one.

**Closed by jessepollak** 2016-09-19 00:13 UTC
Labels: bug
