### ISSUE TITLE
Expiration Date issue on Android Devices

### ISSUE THREAD

**Issue by mahdera** [jessepollak/card#477] opened 2020-12-01 01:45 UTC
I am getting the following error when using card on android devices:
![galaxy-issue](https://user-images.githubusercontent.com/4753816/100686731-eeb06200-334c-11eb-8737-19dd0ddc557c.jpg)

**Comment by melloware** [comment] 2020-12-05 18:00
Duplicate of https://github.com/jessepollak/card/issues/387 ??

Can you try the solution posted using `<input type="tel"..` instead of `text.

**Closed** 2020-12-10 12:47 UTC
Labels: bug
