### ISSUE TITLE
Card form on mobile

### ISSUE THREAD

**Issue by OriginersMc** [jessepollak/card#462] opened 2020-06-10 21:21 UTC
Hi

I added this plugin on my website and all works fine except one thing.

The same form on mobile device, can be breaked and user can add unlimited characters on number field and letters on it.
Valid date can be bypassed and writte unlimited characters too.

How I can fix that?

Best regards

**Comment by msaad1234** [comment] 2020-06-11 21:52
Hello

You can limit the number of characters either using the programming language or using HTML's maxLength property of <input />

try javascript also to limit the number of characters

for the date, you can use Regular Expression to validate it 

I hope it's helpful

**Comment by gabrielcpolidoro** [comment] 2020-07-07 18:41
Not sure if this could help you, but I had an CSS trouble with the card wrapper. On devices with min-width less than 450px, the layout corrupts and the card goes "outside" of the screen.

My counter for this issue was to add some CSS:

```
@media (max-width: 450px) {
  .card-wrapper {
    max-width: 80vw;
    width: 100%;
    margin: 20px auto;
    overflow-x: hidden;
  }

  .card-wrapper > .jp-card-container {
    transform: scale(0.625);
    transform-origin: left center;
  }
}
```

**Comment by melloware** [comment] 2020-12-03 16:01
duplicate of https://github.com/jessepollak/card/issues/463

**Closed by melloware** 2020-12-03 16:01 UTC
Labels: duplicate
