### ISSUE TITLE
any way to use posted data?

### ISSUE THREAD

**Issue by huglester** [jessepollak/card#250] opened 2016-05-24 12:28 UTC
Hello,

so Imagine I have all those input fields, and my internal validation.
and after posting, I hane input with value of 'First name' for example.

But this data is not put into the 'generated image', untill I start typing into the <input> field.

I tried various $('input').trigger('change'); click, keyup etc, nothing worked. Any workaround on this?

**Comment by lazharichir** [comment] 2016-08-18 20:25
Same issue here (for the name..)

**Comment by Iftahh** [comment] 2016-09-12 08:44
I suggest you change the title of the question to some better -  the title should describe there is a problem with the initial render using initial values.

seems there is code to handle that but the code is broken - should be an easy fix

in `Card.prototype.handleInitialPlaceholders`  

the code works if "el" is a single element, but it is an array containing a single element istead...
```
    if (QJ.val(el)) {    // <--- this line fails to fetch the value of `el`
	        QJ.trigger(el, 'paste');
	        results.push(setTimeout(function() {
	          return QJ.trigger(el, 'keyup');
	        }));
```

**Comment by jessepollak** [comment] 2016-09-19 00:12
This is a duplicate of #184 - would love to see a PR to make this easier! Thanks for opening the issue.

**Closed by jessepollak** 2016-09-19 00:12 UTC
